please:
	g++ -std=c++11 main.c++ -I/home/johnwick/Documents/nnp/Interface@2/nn_f_c/include -L/home/johnwick/Documents/nnp/Interface@2/nn_f_c/lib -lcontinue_training -lClassifier -lMisc -lClassifier -lConstructor -lsetErrors -lfeedForward -lBackpropogation -lMath -lMatrix -lLayer -lNeuron -lNeuralNetwork -lSaveWeights -o main
